baseurl = "/"
title = "Essence Learning"
theme = "hugo-universal-theme"

publishDir = "docs"

[languages.en.params]
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
    defaultContentLanguage = "en"
    contactName = "Name1"

# Enable comments by entering your Disqus shortname
disqusShortname = "essencelearningwp"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-NPTFN9RQ9G"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Courses"
    url  = "/courses/"
    identifier = "menu.courses"
    weight = 3

[[menu.main]]
    name = "Regular Courses"
    url  = "/courses/"
    weight = 1
    parent = "menu.courses"

[[menu.main]]
    name = "Introductory Pilot Course"
    url  = "/introcourse/"
    weight = 2
    parent = "menu.courses"    

[[menu.main]]
    name = "Team"
    url  = "/team/"
    weight = 4

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/EssenceLearningBangalore"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:info@essencelearning.in"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "http://www.linkedin.com/in/essencelearning"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 4
    name = "Phone"
    url = "tel:+919663178645"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Essence Learning"
    defaultKeywords = ["aviation", "hospitality", "ground staff", "Training"]
    defaultDescription = "Essence Learning - Aviation and Hospitality Institute"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@essencelearning.in"

    about_us = """<p>Essence Learning is Aviation and Hospitality Vocational Training and Placement Institute to provide quality affordable training in this field.<br><br> <b>You can download detailed course information <a href="/courses/ELCourses2018.pdf" target="_blank" download>here</a></b></p>"""
    copyright = "Copyright (c) 2023 - 2024, Essence Learning; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/el/ELLogoJuly2023.jpg"
    logo_small = "img/el/ELLogoJuly2023.jpg"
    
    address = """<p><strong>Essence Learning</strong>
    <br>One Co.Work
    <br>2/3, 2nd Floor, 80 Feet Road, Barleyz Junction
    <br>Sony world crossing, Koramangala,
    <br>Bangalore, 560034
    <strong>India</strong>
    <br>Phone: <a href="tel:+919663178645">+91 96631 78645</a> / <a href="tel:+917019571290">+91 70195 71290</a>
    <br> <b><a href="https://goo.gl/maps/mUkDk4SqiVb7Wae28" target="_blank">View Map</a></b>
    </p>"""

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Call us on <a href="tel:+919663178645">+91 96631 78645</a> / <a href="tel:+917019571290">+91 70195 71290</a> or mail us <a href="mailto:info@essencelearning.in">info@essencelearning.in</a></p>
    """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # title = "Courses"
    subtitle = """SKILLING PARTNER OF <a href="https://www.juxhub.com" target ="_blank">JAINx</a> AND PROGRAMS ENDORSED BY <a href="https://www.jainuniversity.ac.in/" target ="_blank">JAIN (DEEMED-TO-BE UNIVERSITY)</a> FOR TRAINING IN """
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have helped many Aviation and Hospitality aspirants realize their dream. Have a look what our students said about us."

[params.see_more]
    enable = true
    icon = "fa fa-certificate"
    title = ""
    subtitle = "CERTIFIED BY JAINx AND JAIN (DEEMED-TO-BE UNIVERSITY)"
    link_url1 = "https://www.juxhub.com/"
    link_url2 = "https://www.jainuniversity.ac.in/"
    link_text1 = "SKILLING PARTNER"
    link_text2 = ""
    img1 = "img/el/jainx-logo.png"
    img2 = "img/el/jain-logo jgi.png"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Certified by JAINx and JAIN (Deemed-to-be University)"
    subtitle = ""

[params.team]
    enable = true
    # Copied from the clients above
    title = "Our Team"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "We love spreading love about Aviation and Hospitality through our blogs and articles."

[markup.goldmark.renderer]
    unsafe=true

